### ISSUE TITLE
Add Distance Along Cross Section to Interpolate to Slice 

### ISSUE THREAD

**Issue by walterjhudson** [walterjhudson/CSC_6110_MetPy#3]
### What should we add?

|Add Distance Along Cross Section to Interpolate to Slice |
|----------------------|
| **Estimate:** 5 |
| **Priority:** Should have |
|**Story**: **As a** researcher using the application to do plotting and visualization, **I want** to get the range of the slice along with their exact distances after slicing my data set **so that I** can visualize my data easily without having to hack onto the dataset .|
| **Acceptance criteria:** |
|**Given** sliced data from metpy.interpolate.cross_section and metpy.interpolate.interpolate_to_slice|
|**When** [“distance”] is called on this data| 
|**Then** we get the range and distance of the slices|

**Comment by LucilleGallet** [comment]
Tasks : 
1. Compile metpy and test different functions to understand its goals and limitations [3 hours] : done
2. Research the Interpolate to Slice function [1.5 hours] : done
3. Locate source code [1 hour] : done
4. Test the function [1 hour]
5. Modify the code [2.5 hours]
6. Find a data set to test the code [1 hour]
7. Create a unit test [1 hour]
8. Update doc [1 hour]
Total : 12 hours
